name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: gcp
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      # Set GCP credentials
    - name: Set GCP credentials
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5

    - name: Initialize Terraform
      run: cd test && terraform init

    - name: Plan Terraform changes
      run: cd test && terraform plan -var="data_ingestion_project_id=${{ secrets.GCP_PROJECT_ID }}" -var="data_ingestion_project_region=${{ secrets.GCP_PROJECT_REGION }}"
    
    - name: Apply Terraform changes
      run: cd test && terraform apply -var="data_ingestion_project_id=${{ secrets.GCP_PROJECT_ID }}" -var="data_ingestion_project_region=${{ secrets.GCP_PROJECT_REGION }}" --auto-approve
